typeof(comuni_aggiornato)
ncol(comuni_aggiornato)
nrow(comuni_aggiornato)
nrow(elenco_comuni)
comuninew1 <-dplyr::right_join(comuni_aggiornato, elenco_comuni, by = "Comune")
comuninew <-dplyr::full_join(comuni_aggiornato, elenco_comuni, by = "Comune")
summary(comuninew1)
head(comuninew1)
read.csv(comuninew)
head(comuni_aggiornato)
tolower(comuni_aggiornato([2]))
comuni_lower <-data.frame(tolower(comuni_aggiornato$Comune))
head(comuni_lower)
comuni_lower2 <-data.frame(tolower(elenco_comuni$Comune))
elenco_comuni_new <- iconv(elenco_comuni, 'UTF-8', 'ASCII')
head(elenco_comuni_new)
head(elenco_comuni)          
elenco_comuni<- iconv(elenco_comuni$Comune, "ASCII", "UTF-8", sub="byte")
head(elenco_comuni)
