ncol(conte_1)
ncol(conte_2)
merged_conte <- dplyr::union(conte_1, conte_2)
new_merged_conte <- count(merged_conte, "sentiment class")
tally(sentiment class)
count("sentiment class", merged_conte)
merged_conte %>% count(`sentiment class`)
merged_data <- bind_rows(conte_1, conte_2)
merged_data_1 <-dplyr::bind_rows(conte_1, conte_2)
